---
#Update apt packages list
- name: Update apt (apt-get update)
  apt: update_cache=yes

#Upgrade packages
- name: Upgrade packages (apt-get upgrade)
  apt: upgrade=dist

#Ensure sudo is installed
- name: Install sudo
  apt:
    pkg: sudo
    state: latest

#Create a new user
- name: Create user muratso
  user:
    name: muratso
    append: yes
    groups: sudo
    state: present
    password: $6$vxck6f8otidD$V6rqAtVHM0gL/vY1GKAZl8Q6xbvSUQ1I0h6J5FF/6bThN4kgtZ8njuWJA3wucGUvvTz6Y1hDoPBdiQbhUkNSq.
    shell: /bin/bash

#Install base packages
- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - wget
    - vim
    - git
